[project]
name = "sqlite-to-erd"
version = "0.3.0"
description = "Generate ERD diagrams from SQLite databases"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
]

[project.scripts]
sqlite-to-erd = "sqlite_to_erd:main"
